export const users = [
  { 
    name: 'Dada Teslim', 
    country: 'Nigeria', 
    avatar: '👨🏿',
    comment: 'FolioSpace helped me land my dream job! The ATS optimization is incredible.',
  },
  { 
    name: 'Afolayan Azeemat', 
    country: 'Nigeria', 
    avatar: '👩🏿',
    comment: 'Created my CV in 5 minutes. So easy to use and professional!',
  },
  { 
    name: 'Bamidele Temitayo', 
    country: 'Nigeria', 
    avatar: '👨🏿',
    comment: 'Finally got interview calls after using FolioSpace. Highly recommend!',
  },
  { 
    name: 'Olorode Qudus', 
    country: 'Nigeria', 
    avatar: '👨🏿',
    comment: 'Best CV builder I\'ve ever used. Clean, professional, and ATS-friendly.',
  },
  { 
    name: 'Olusanya Mary', 
    country: 'Nigeria', 
    avatar: '👨🏿',
    comment: 'Best CV builder I\'ve ever used. Clean, professional, and ATS-friendly.',
  },
  { 
    name: 'Oluwaseun Adeyemi', 
    country: 'Nigeria', 
    avatar: '👩🏿',
    comment: 'Got 3 job offers within a week! FolioSpace is a game changer.',
  },
  { 
    name: 'Chinonso Obi', 
    country: 'Nigeria', 
    avatar: '👨🏾',
    comment: 'The templates are stunning and the export quality is perfect.',
  },
  { 
    name: 'Temidayo Ojo', 
    country: 'Nigeria', 
    avatar: '👩🏾',
    comment: 'Finally a CV builder that actually works! Thank you FolioSpace!',
  },
  { 
    name: 'Ngozi Nwankwo', 
    country: 'Nigeria', 
    avatar: '👩🏿',
    comment: 'My recruiter said my CV looks amazing. All thanks to FolioSpace!',
  },
  { 
    name: 'David Smith', 
    country: 'USA', 
    avatar: '👨🏻',
    comment: 'Impressed by how professional my resume looks now. Worth every penny!',
  },
  { 
    name: 'Maria Garcia', 
    country: 'Spain', 
    avatar: '👩🏻',
    comment: 'Simple, fast, and effective. Got my job in tech with this CV!',
  },
  { 
    name: 'Emma Johnson', 
    country: 'UK', 
    avatar: '👩🏼',
    comment: 'The ATS optimization helped me pass the initial screening. Amazing!',
  },
  { 
    name: 'Pierre Dubois', 
    country: 'France', 
    avatar: '👨🏼',
    comment: 'Professional quality without the hassle. FolioSpace is brilliant!',
  },
  { 
    name: 'Anna Kowalski', 
    country: 'Poland', 
    avatar: '👩🏼',
    comment: 'Created multiple CVs for different roles. So convenient!',
  },
  { 
    name: 'Lucas Santos', 
    country: 'Portugal', 
    avatar: '👨🏻',
    comment: 'My job search became so much easier with FolioSpace. 5 stars!',
  },
  { 
    name: 'Sofia Martinez', 
    country: 'Mexico', 
    avatar: '👩🏽',
    comment: 'Beautiful templates and super easy to customize. Love it!',
  },
  { 
    name: 'Kim Min-jun', 
    country: 'South Korea', 
    avatar: '👨🏻',
    comment: 'Got my first international job thanks to this professional CV!',
  },
  { 
    name: 'Isabella Rossi', 
    country: 'Italy', 
    avatar: '👩🏻',
    comment: 'The best investment for my career. Highly professional results!',
  },
  { 
    name: 'Aisha Okafor', 
    country: 'Nigeria', 
    avatar: '👩🏿',
    comment: 'Switched from another builder to FolioSpace. No regrets!',
  },
  { 
    name: 'Raj Patel', 
    country: 'India', 
    avatar: '👨🏾',
    comment: 'Clean interface, professional output. Exactly what I needed!',
  },
  { 
    name: 'Leila Hassan', 
    country: 'Lebanon', 
    avatar: '👩🏽',
    comment: 'Made my resume stand out! Started getting calls immediately.',
  },
];